config/routes.rb
Rails.application.routes.draw do
  root to: 'phone#index'
  get 'phone/index'
  post 'phone/product'
  post 'phone/product_details'
  post 'phone/search'
  

end

app/models/brand.rb
class Brand
	# brand name of the phone
	require 'open-uri'
  include ActiveModel::Model
  attr_accessor :id, :name, :link

  validates_presence_of :id, :name, :link

  def self.all_from_gsmarena 
    # all phone's brands from http://www.gsmarena.com
		source = "http://www.gsmarena.com/makers.php3"
	  source_base = "http://www.gsmarena.com/"
	  html_doc = Nokogiri::HTML(open(source))

	  rows = []
	  html_doc.xpath('//*/table/tr/td[2]').each_with_index do |row, i|
	  	if row.css('a')[0].present?        
        brand = Brand.new(id: i + 1, name: row.text, link: source_base + row.css('a')[0]["href"])
	      rows << brand
		  end
	  end
	  return rows
  end

end

app/models/phone.rb
class Phone
	require 'open-uri'
  include ActiveModel::Model
  attr_accessor :id, :name, :link

  validates_presence_of :id, :name, :link

  def self.from_gsmarena(source)
  	# full name and link of the phone from http://www.gsmarena.com
	  source_base = "http://www.gsmarena.com/"
	  html_doc = Nokogiri::HTML(open(source))

	  rows = []
     html_doc.css('div.makers li').each_with_index do |row, i|
    	if row.css('a')[0].present?
    		phone = Phone.new(id: i + 1, name: row.text, link: source_base + row.css('a')[0]["href"])
		    rows << phone
		  end
    end
	  return rows
  end

end

app/models/phone_detail.rb
class PhoneDetail
	require 'open-uri'
  # include ActiveModel::Model
  # attr_accessor :id, :name, :link

  # validates_presence_of :id, :name, :link

  def self.image_from_gsmarena(source)
	  source_base = "http://www.gsmarena.com/"
	  html_doc = Nokogiri::HTML(open(source))

    details_image = html_doc.css('div.specs-photo-main').to_html
    return details_image
  end

  def self.details_from_gsmarena(source)
	  source_base = "http://www.gsmarena.com/"
	  html_doc = Nokogiri::HTML(open(source))

    details = html_doc.css("#specs-list").to_html
    return details
  end


end

app/models/search.rb
class Search
	require 'open-uri'
  include ActiveModel::Model
  attr_accessor :id, :name, :link

  validates_presence_of :id, :name, :link

  def self.from_gsmarena(search_string)
		source = "http://www.gsmarena.com/results.php3?sQuickSearch=yes&sName=#{search_string}"
    source_base = "http://www.gsmarena.com/"
	  html_doc = Nokogiri::HTML(open(source))

	  rows = []
     html_doc.css('div#review-body li').each_with_index do |row, i|
    	if row.css('a')[0].present?
    		phone = Phone.new(id: i + 1, name: row.text, link: source_base + row.css('a')[0]["href"])
		    rows << phone
		  end
    end
	  return rows
  end
  
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/phone_controller.rb
class PhoneController < ApplicationController
  respond_to :html, :js

  def index
  	@brands = Brand.all_from_gsmarena
  end

  def product
    brands = Brand.all_from_gsmarena
    @source_brand = brands[params[:brand].to_i - 1].link
    @phones = Phone.from_gsmarena(@source_brand)
  end

  def product_details
    if params[:source].present?
  	  phones = Phone.from_gsmarena(params[:source])
    else
      phones = Search.from_gsmarena(params[:search_string])
    end
    source_detail = phones[params[:phone].to_i - 1].link
    @product_image = PhoneDetail.image_from_gsmarena(source_detail)
    @product_details = PhoneDetail.details_from_gsmarena(source_detail)
  end

  def search
    @phones = Search.from_gsmarena(params[:search_string])
    @search_string = params[:search_string]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/phone_helper.rb
module PhoneHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhonesApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/phone/_detail_form.html.slim
= render inline: @product_image
= render inline: @product_details

app/views/phone/_form.html.slim
/ p = "Brand_id = #{params[:brand].to_i}"
/ p = "Link #{@source_brand}"
/ p = "The total number of phones: #{@phones.count}." 

= form_tag phone_product_details_path, method: :post, remote: true do |f|
  = label_tag "Select phone: "
  br
  = select_tag "phone", options_for_select(@phones.collect{ |phone| [phone.name, phone.id]})
  = hidden_field_tag(:source, @source_brand)
  = hidden_field_tag(:search_string, @search_string)  
  p = submit_tag "Submit phone"

app/views/phone/index.html.slim
#controls
	/ p = "The total number of brands: #{@brands.count}."
	#clear 
	#brand_form
		= form_tag phone_product_path, method: :post, remote: true do |f|
		  = label_tag "Select brand name: "
		  br
		  = select_tag "brand", options_for_select(@brands.collect{ |brand| [brand.name, brand.id]})
		  p = submit_tag "Submit brand name"
	#search_form
		= form_tag phone_search_path, method: :post, remote: true do |f|
		  = label_tag "Search for: "
		  br
		  = text_field_tag :search_string
		  p = submit_tag "Go"
	#clear 
	#phone_form style="display:none;"
#detail_form style="display:none;"

app/views/phone/product.js.erb
$('#phone_form').html("<%= j (render 'phone/form') %>");
$('#phone_form').slideDown(400);

app/views/phone/product_details.js.erb
$('#detail_form').html("<%= j (render 'phone/detail_form') %>");
$('#detail_form').slideDown(400);

app/views/phone/search.js.erb
$('#phone_form').html("<%= j (render 'phone/form') %>");
$('#phone_form').slideDown(400);